PUP_LMS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('system.urls')),
    path('accounts/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
 
    path('', include('crud.urls')),
    path('', include('posts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crud/urls.py
from django.urls import path
from . import views



urlpatterns = [
    # path('courses/',views.course, name="course-list"),
    path('class-detail/<int:class_id>/',views.class_detail, name="class-detail"),
    path('class-delete/<int:class_id>/',views.class_delete, name="class-delete"),
    path('class-update/<int:class_id>/',views.class_update, name="class-update"),
    path('class-create/',views.class_create, name="class-create"),
    path('administration/',views.administration, name="administration"),
 
   
    #create quiz
    path('create-quiz/<int:class_id>/',views.create_quiz, name='create-quiz'),
    path('create-question/<int:quiz_id>/',views.create_question, name='create-question'),
    
    path('question-update/<int:question_id>/',views.question_update, name='question-update'),
    path('question-delete/<int:question_id>/',views.question_delete, name='question-delete'),
    #create choices
    path('create-choice/<int:question_id>/',views.create_choice, name='create-choice'),
    #choice detail
    path('choice-detail/<int:choice_id>/',views.choice_detail, name='choice-detail'),
    #choice update
    path('choice-update/<int:choice_id>/',views.choice_update, name='update-choice'),
    #choice delete
    path('choice-delete/<int:choice_id>/',views.choice_delete, name='delete-choice'),
    #quiz
    #list
    path('quiz-list/<int:class_id>/',views.quiz_list, name='quiz-list'),
    #result
    path('quiz-results/<int:quiz_id>/',views.quiz_results, name='quiz-results'),
    #detail
    path('quiz-detail/<int:quiz_id>/',views.quiz_detail, name='quiz-detail'),
    #update
    path('quiz-update/<int:quiz_id>/',views.quiz_update, name='quiz-update'),
    #delete
    path('quiz-delete/<int:quiz_id>/',views.quiz_delete, name='quiz-delete'),
   
]

system/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('registration/',views.landing_page, name="landing-page"),
    path('',views.index, name="index"),
    path('student-class-list/',views.student_class_list, name="student-class-list"),
    path('student-class-detail/<int:class_id>/', views.student_class_detail, name="student-class-detail"),
    path('take-quiz/<int:quiz_id>/', views.take_quiz, name="take-quiz"),
  
    path('quiz/<int:quiz_id>/results', views.show_results, name="show-results"),
    path('announcement-create/', views.announcement_create, name="create-announcement"),
    path('announcement-list/', views.announcement_list, name="announcement-list"),
    path('announcement-detail/<int:announcement_id>', views.announcement_detail, name="announcement-detail"),
    path('announcement-delete/<int:announcement_id>', views.announcement_delete, name="delete-announcement"),
    path('announcement-update/<int:announcement_id>', views.announcement_update, name="update-announcement"),
    

]

crud/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone

class ClassName(models.Model):
    title = models.CharField(verbose_name= 'Class', max_length=100)
    subject= models.CharField(verbose_name= 'Subject', max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE, related_name='author')
    class_code = models.CharField(max_length=20) 
    student = models.ManyToManyField(User)
    
    class Meta:
        verbose_name_plural = 'classes'

    def __str__(self):
        return self.title


class Quiz(models.Model):
    text = models.CharField(verbose_name='Quiz Title',max_length=100)
    classname = models.ForeignKey(ClassName, on_delete = models.CASCADE)

    def __str__(self):
        return self.text
class Question(models.Model):
    text = models.CharField(verbose_name='question',max_length=100)
    quiz = models.ForeignKey(Quiz, on_delete = models.CASCADE)

    def __str__(self):
        return self.text

class Choice(models.Model):
    text = models.CharField(verbose_name='Choice',max_length=100)
    question = models.ForeignKey(Question,on_delete = models.CASCADE)
    correct = models.BooleanField()
    
    def __str__(self):
        return self.text


class UserAnswer(models.Model):
    question = models.ForeignKey(Question, related_name='question',on_delete = models.CASCADE)
    answer = models.ForeignKey(Choice, on_delete = models.CASCADE,verbose_name='',related_name='answer', default='')
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    quiz = models.ForeignKey(Quiz,on_delete = models.CASCADE, default = '')
 

    # class Meta:
    #     unique_together = ['question','answer']
        
    def __str__(self):
        return f'{self.question.text}-{self.answer.text}'

class QuizResult(models.Model):
    quiz = models.ForeignKey(Quiz,on_delete = models.CASCADE,null = True)
    user = models.ForeignKey(User, on_delete = models.CASCADE,null = True)
    score = models.IntegerField(null = True)
    total_score = models.IntegerField(null = True)
    percent = models.DecimalField(max_digits=19,decimal_places = 2,null = True)
    status = models.BooleanField(null = True)
    

    def __str__(self):
        return f'{self.quiz} - {self.user}'


class Announcement(models.Model):
    classname = models.ForeignKey(ClassName,on_delete = models.CASCADE)
    title = models.CharField(max_length = 255,default='')
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add = True)
    due = models.DateTimeField()
    author = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):
        return self.title

  



    

system/models.py
from django.db import models

system/forms.py
from crud.models import ClassName,Quiz,Question,Choice,UserAnswer
from django import forms
class UserAnswerForm(forms.ModelForm):
    
    class Meta:
        model = UserAnswer
        fields = ['answer']
    

system/views.py
from django.shortcuts import render,redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponseRedirect
from crud.models import *
from django.db import IntegrityError, transaction
from django.core.exceptions import PermissionDenied, SuspiciousOperation
from users.forms import ClassCode
from django.urls import reverse
from system.forms import UserAnswerForm
from crud.forms import ChoiceForm,AnnouncementForm
from crud.models import Announcement
from posts.models import Post
from posts.forms import PostForm
# from posts.models import Post

@login_required
def index(request):
    student = request.user
    user_classname = ClassName.objects.filter(student=student)  
    class_author = ClassName.objects.filter(author = request.user)
    student_class = ClassName.objects.filter(student = request.user)
    class_code_list = []
    class_list = ClassName.objects.all()
    student_class = []
    for key,item in enumerate(user_classname,start=1):
        student_class.append(item)
        if key ==3:
            break
    for item in class_list:
        class_code_list.append(item.class_code)
    print(class_code_list)
    user_allowed = []
    for user in user_classname:
        user_allowed.append(user.student.all())
  
    user_classname_list = student.classname_set.all()    
    posts = Post.objects.all().order_by('-date_posted') 
    paginator = Paginator(posts,2)   
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
 
    announcement = Announcement.objects.filter(classname__student = student)
    events = []
    for key,item in enumerate(announcement,start=1):
        events.append(item)
        if key == 2:
            break
    print(events)
    # print(user_classname)
    
    if request.method == 'POST':
        class_code = request.POST.get('code') 
        if class_code in class_code_list:
            student = request.user
            classname = ClassName.objects.get(class_code = class_code)
            classname.student.add(student)
            messages.success(request,f'You are now enrolled in class {classname}')
            return redirect('index')
        else:
            messages.error(request,f'Invalid class code. Please try again')
            return redirect('index')

    context = {
        'announcement':events,
        'class':student_class,
        'class_count':len(student_class),
        'posts':posts,
        'user_allowed':user_allowed,
        'user_classname_list':user_classname_list,
        'class_author':class_author,
        'student_class':student_class,
        'page_obj': page_obj
    }
    return render(request,'system/index.html',context)
   
@login_required
def student_class_list(request):
    student = request.user
    class_list = ClassName.objects.filter(student = request.user)
    
    # print(class_list)
    student_classes = student.classname_set.all()
    
    context={
        'class_list':class_list,
    }
    return render(request,'system/student_class_list.html',context)



def landing_page(request):
 
    return render(request,'system/landing_page.html')
   

@login_required
def student_class_detail(request,class_id):
    classname = ClassName.objects.get(id = class_id)
    quiz_list = Quiz.objects.filter(classname = classname)
    user = request.user
    student_list = classname.student.all()
    is_taken = UserAnswer.objects.filter(user = request.user.id)
    # for item in is_taken:
    #     print(item.user)
    # print(is_taken)
    in_useranswer = []
    for quiz in quiz_list:
        quiz_done = quiz.useranswer_set.filter(user = request.user).filter(quiz = quiz)       
        for item in quiz_done:
            in_useranswer.append(item.quiz)
        print(in_useranswer)
   
    stud_list = []
    for key,student in enumerate(student_list,start=1):
        stud_list.append((key,student))
    context={
        'is_taken':is_taken,
        'class':classname,
        'quiz':quiz_list,
        'student':stud_list,        
        'user':user, 
        'in_useranswer':in_useranswer,       
        
    }
    return render(request,'system/student_class_detail.html',context)

#student take quiz
@login_required
def take_quiz(request, quiz_id):
    quiz = Quiz.objects.get(id = quiz_id)
    classname = ClassName.objects.get(quiz = quiz)
    question = Question.objects.filter(quiz = quiz)
    student = request.user
    
    print(UserAnswer.objects.all())
    if request.method == 'POST':
        with transaction.atomic():
            UserAnswer.objects.filter(user=request.user,
                                    question__quiz=quiz).delete()
            for key, value in request.POST.items():
                if key == 'csrfmiddlewaretoken':
                    continue
                #{'question-1':2}
                question_id = key.split('-')[1]
                question = Question.objects.get(id=question_id)
                answer_id = int(request.POST.get(key))
                if answer_id not in question.choice_set.values_list('id',flat=True):
                    raise SuspiciousOperation('Answer is not valid for this question')
                
               
                user_answer = UserAnswer.objects.filter(question = question).filter(answer_id = answer_id).filter(user = request.user)
                if user_answer:
                    user_answer.user = request.user,
                    user_answer.question = question,
                    user_answer.answer_id = answer_id,
                    user_answer.quiz = quiz
                    user_answer.save()
                else:
                    user_answer = UserAnswer.objects.create(
                        user = request.user,
                        question=question,
                        answer_id = answer_id,
                        quiz = quiz
                    )
             
                   
        return redirect(reverse('show-results',args=(quiz.id,)))  
    
    question_list = []
    for key,question in enumerate(question,start=1):
        question_list.append((key,question))

    context={
        'quiz':quiz,
        'class':classname,
        'question':question_list,
        'student':student,
       
    }
    return render(request,'system/take_quiz.html',context)

def calculate_score(user, quiz):
    questions = Question.objects.filter(quiz=quiz)
    correct_answers = UserAnswer.objects.filter(
        user=user,
        question__quiz=quiz,
        answer__correct=True
    )
 
    percent = round((correct_answers.count() / questions.count()) * 100,2)
    score = correct_answers.count()
    total_score = len(questions)
    
    if percent >= 50:
        passed = True
    else:
        passed = False
    print(passed)
    score_list = {
        'score':score,
        'total_score':total_score,
        'percent':percent
    }
    result = QuizResult.objects.filter(quiz = quiz).filter(user=user)
    if result:
        result.quiz = quiz,
        result.user = user,
        result.score = score,
        result.total_score = total_score,
        result.percent = percent,
        result.status = passed
        result.update()
    else:
        quiz_result = QuizResult.objects.create(
                        quiz = quiz,
                        user = user,
                        score = score,
                        total_score = total_score,
                        percent = percent,
                        status = passed
                )
        quiz_result.save()

    # return f'{score} / {total_score} - {percent} %'
    return score_list
@login_required
def show_results(request, quiz_id):
    # if not request.user.is_authenticated():
    #     raise PermissionDenied
    quiz = Quiz.objects.get(id=quiz_id)
    classname = ClassName.objects.get(quiz = quiz)
    student = request.user
    user_answer = UserAnswer.objects.filter(
        user = request.user,
        question__quiz=quiz
    )
    answer_list = []
    for key,value in enumerate(user_answer,start=1):
        answer_list.append((key,value))
    
    score_list = calculate_score(request.user, quiz)
    score = score_list['score']                
    total_score = score_list['total_score']                
    percent = score_list['percent']                
    context ={
        'quiz':quiz,
        'score':score,
        'total_score':total_score,
        'percent':percent,
        'user_answer':answer_list,
        'student':student,
        'class':classname,
    }
    return render(request,'system/show_results.html',context)

@login_required
def announcement_create(request):
    all_classes = ClassName.objects.filter(author = request.user)
    form = AnnouncementForm()
    # print(form.author)
    if request.method == 'POST':
        form = AnnouncementForm(request.POST)
        if form.is_valid():
            form.save(commit = False)
            form.author = request.POST.get('author')
            form.save()
            messages.success(request,f'A new announcement has been created')
            return redirect('announcement-list')
        else:
            messages.error(request,f'An error occured.Please try again. Invalid date and time format.')
            print(form.errors.as_data())


    context={
        'form':form,
        'classes':all_classes,
    }
    return render(request,'system/announcement_create.html',context)

@login_required
def announcement_list(request):
    announcements = Announcement.objects.filter(author = request.user)
    print(announcements)
   

    context={
        'announcements':announcements,
    }
    return render(request,'system/announcement_list.html',context)

@login_required
def announcement_delete(request,announcement_id):
    announcement = Announcement.objects.get(id = announcement_id)
    if request.method == 'POST':
        announcement.delete()

system/templates/system/announcement_create.html
{% extends 'system/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block content%}
    <div class="row pl-2">  
        <div class="col-md-3  pt-3 pl-2 sidebar">
            {% include 'crud/sidebar.html' %}
        </div>

        <div class="col-md-8 col-sm-12 section-container">
            {%if messages%}
            {%for message in messages%}
                {%if message.tags == 'success'%}
                    <p class="alert alert-success d-flex align-items-center"style="min-height:20px!important ">{{message}}</p>
                {%else%}
                    <p class="alert alert-danger d-flex align-items-center"style="min-height:20px!important">{{message}}</p>
                {%endif%}
            {% endfor %}
        {% endif %}
            <h2>Add Announcement</h2>
            <form method="POST">
                {%csrf_token%}
                <select name="classname" required id="id_classname" class="form-control"required>
                    <option value="" selected="">----   Choose Class   -----</option>
                    {% for class in classes%}
                        <option value="{{class.id}}">{{class}}</option>
                    {%endfor%}
                  
                </select>
               {{form.title|as_crispy_field}}
               {{form.text|as_crispy_field}}
               <input type="hidden" name="author" value="{{request.user.id}}" id="id_author">
                
              
             
                {% comment %} Due: {%render_field form.due id="datetimepicker" class="form-control"%} {% endcomment %}
                Due: {%render_field form.due class="form-control" placeholder="e.g. 2020-01-01 10:00:00 (year-day-month hour:minutes:seconds)"%}
                <!-- Due : <input type="text" name="due" class="datetimeinput" required="" id="datetimepicker"> -->
               
                <div class="modal-footer">
                    <button type="submit" class="btn btn-warning text-light ">Create</button>
                    <a href="{% url 'announcement-list' %}" class="btn btn-secondary" data-dismiss="modal">Cancel</a>
                </div>
            </form>    
        </div>
    </div>
    
     
{% endblock content%}

system/templates/system/announcement_delete.html
{% extends 'system/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block content%}
    <div class="row pl-2">  
        <div class="col-md-3  pt-3 pl-2 sidebar">
            {% include 'crud/sidebar.html' %}
        </div>

        <div class="col-md-8 col-sm-12 bg-white section-container">
            {%if messages%}
            {%for message in messages%}
                {%if message.tags == 'success'%}
                    <p class="alert alert-success d-flex align-items-center"style="min-height:20px!important ">{{message}}</p>
                {%else%}
                    <p class="alert alert-danger d-flex align-items-center"style="min-height:20px!important">{{message}}</p>
                {%endif%}
            {% endfor %}
        {% endif %}
            <h2> Are you sure you want to delete this announcement?</h2><br>
            <h5 class="text-muted">Summary</h5>
            
            <div>
                Title: {{announcement.title}}
            </div> 
            <div>
                Text: {{announcement.text}}
            </div> 
            <div>
                Due: {{announcement.due}}
            </div> 
           
            <form method="POST">
                {%csrf_token%}
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger text-white" data-dismiss="modal">Delete</button>
                    <a href="{% url 'announcement-list'%}" class="btn btn-secondary" data-dismiss="modal">Cancel</a>
                </div>
            </form>
            
        </div>
    </div>
    
     
{% endblock content%}

system/templates/system/announcement_detail.html
{% extends 'system/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block content%}
    <div class="row pl-2">  
        <div class="col-md-3  pt-3 pl-2 sidebar">
            {% include 'crud/sidebar.html' %}
        </div>

        <div class="col-md-8 col-sm-12 section-container">
            {%if messages%}
            {%for message in messages%}
                {%if message.tags == 'success'%}
                    <p class="alert alert-success d-flex align-items-center"style="min-height:20px!important ">{{message}}</p>
                {%else%}
                    <p class="alert alert-danger d-flex align-items-center"style="min-height:20px!important">{{message}}</p>
                {%endif%}
            {% endfor %}
        {% endif %}
        <button class=" text-white bg-secondary pl-1 pr-1 align-items-center mb-3 justify-content-center">
            <a href="{% url 'announcement-list' %}" class="text-white">
                Back
            </a>
        </button>
           
            {%if announcement%}
                            
                    <div class="row border-top">
                        <div class="col-md-6">
                            <div class="d-flex align-items-center">
                                <p class="text-muted mr-5">Title: </p> <h2>{{announcement.title}}</h2>
                            </div>
                            <div class="d-flex align-items-center">
                                <p class="text-muted mr-5">Text: </p> <p>{{announcement.text}}</p>
                            </div>
                            <div class="d-flex align-items-center">
                                <p class="text-muted mr-5">Due: </p> <p>{{announcement.due}}</p>
                            </div>
                        </div>
                        
                    </div>
                
            {%else%}
                <h3 class=text-center>No Announcement Yet</h3>
            {%endif%}
           
        </div>
    </div>
    
     
{% endblock content%}

system/templates/system/announcement_list.html
{% extends 'system/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block content%}
    <div class="row pl-2">  
        <div class="col-md-3  pt-3 pl-2 sidebar">
            {% include 'crud/sidebar.html' %}
        </div>

        <div class="col-md-8 col-sm-12 section-container">
            {%if messages%}
            {%for message in messages%}
                {%if message.tags == 'success'%}
                    <p class="alert alert-success d-flex align-items-center"style="min-height:20px!important ">{{message}}</p>
                {%else%}
                    <p class="alert alert-danger d-flex align-items-center"style="min-height:20px!important">{{message}}</p>
                {%endif%}
            {% endfor %}
        {% endif %}
            <h2> Announcements</h2>
            {%if announcements%}
            <ul class="list-group">
                <li class="list-group-item mb-2">
                    <div class="row">
                        <div class="col">
                            
                            <ol type="1">
                                {% for item in announcements%}
                                <div class="row mb-2">
                                    <div class="col-md-6 text-info">
                                        <li><a href="{% url 'announcement-detail' item.id%}">{{item.title}} - {{item.classname}}</a></li>
                                    </div>
                                    <div class="col-md-6">
                                        <a href="{% url 'announcement-detail' item.id%}" class="bg-warning text-white ml-2 pl-3 pr-3 align-items-center justify-content-center">
                                            Detail
                                        </a>      
                                        <a href="{% url 'update-announcement' item.id %}" class="bg-secondary text-white ml-2  pl-3 pr-3 align-items-center justify-content-center" data-dismiss="modal">
                                            Edit
                                        </a>
                                        <a href="{% url 'delete-announcement' item.id %}" class="bg-danger text-white ml-2 pl-3 pr-3 align-items-center justify-content-center" data-dismiss="modal">
                                             Delete
                                        </a>                    
                                    </div>
                                     
                                </div>
                                    
                                   
                                {%endfor%} 
                            </ol>                                 
                        </div>
                        
                       
                    </div>
                    
                    
                   
                    
                </li>
            </ul>
                
            {%else%}
                <h5 class=text-center>No Announcement Yet</h5>
            {%endif%}
            <div class="modal-footer">
                
                <a href="{% url 'create-announcement' %}" class="btn btn-warning text-white" data-dismiss="modal">Create</a>
                <a href="{% url 'index' %}" class="btn btn-secondary" data-dismiss="modal">Cancel</a>
            </div>
        </div>
    </div>
    
     
{% endblock content%}

system/templates/system/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'system/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'system/css/sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'system/css/footer.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!--slider-->
    <link type="text/css" href="{%static 'system/css/skitter.css'%}" media="all" rel="stylesheet" />
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="{% static 'system/js/jquery.easing.1.3.js' %}"></script>
    <script type="text/javascript" src="{% static 'system/js/jquery.skitter.min.js'%}"></script>
    <!-- XDSoft DateTimePicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

    
    <title>Learning Management System</title>
</head>

 
<body>    
    {% include 'system/navbar.html'%}   
    
     
    <a href="#" id="scroll" style="display: none;"><span></span></a>
    
    {% if user.is_authenticated %}
        <!-- <div class="container-fluid"> -->
        <div class="p-2 main">
    {% else %}
        <div class="container">
    {% endif %}
            {% block content %}{% endblock content %}
        </div>
        </div>
        <!-- <input id="datetimepicker" type="text"> -->

  <script>
  $(document).ready(function() {
    $(".skitter-large").skitter();
  });
    $(function () {
      $("#datetimepicker").datetimepicker();
    });
  </script>
  
 
    <script src="{% static 'system/js/main.js' %}"></script>
 
   
      {% include 'system/footer.html' %}
   
   

</body>
</html>

system/templates/system/enroll.html
class_code_list = []
    class_list = ClassName.objects.all()
    for item in class_list:
        class_code_list.append(item.class_code)
    

if request.method == 'POST':
        class_code = request.POST.get('code') 
        if class_code in class_code_list:
            student = request.user
            classname = ClassName.objects.get(class_code = class_code)
            classname.student.add(student)
            messages.success(request,f'You are now enrolled in class {classname}')
            return redirect('index')
        else:
            messages.error(request,f'Invalid class code. Please try again')
            return redirect('index')

system/templates/system/student_class_list.html
{% extends 'system/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content%}
    <div class="row justify-content-center">
           {% comment %} <div class="col-3  pt-3 pl-2 sidebar">
            {% include 'system/student_sidebar.html' %}
          </div>  {% endcomment %}
          
          <div class="col-md-8 bg-white p-3"style="min-height:50vh">
           <button class=" text-white bg-secondary pl-1 pr-1 align-items-center mb-3 justify-content-center">
              <a href="{% url 'index' %}" class="text-white">
                  Back
              </a>
          </button>
            <h3>Classes</h3>
            <div class="row ">
             
              
              {% if class_list %}
                {% for class in class_list %}
                  <div class="col-md-3  justify-content-center">
                    <a href="{% url 'student-class-detail' class.id%}">
                      <button class="card bg-warning mb-3 d-flex justify-content-center align-items-center choice-box">
                        <span class="bottom-title">{{class}}</span>
                      </button>
                    </a>
                  </div>
                {%endfor%}
              {%else%}
                   <h4 class="text-muted text-center">No Class Available Yet</h4>
              {%endif%}
            
              
             
            </div>
          </div>
      
        
    </div>
   
     
{% endblock content%}